export enum DriverStatus {
  OFFLINE = 'OFFLINE',
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  ON_TRIP = 'ON_TRIP',
  SUSPENDED = 'SUSPENDED',
}

export enum RideStatus {
  REQUESTED = 'REQUESTED',
  MATCHING = 'MATCHING',
  MATCHED = 'MATCHED',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum CancellationReason {
  RIDER_CANCELLED = 'RIDER_CANCELLED',
  DRIVER_CANCELLED = 'DRIVER_CANCELLED',
  NO_DRIVERS_AVAILABLE = 'NO_DRIVERS_AVAILABLE',
  RIDER_NO_SHOW = 'RIDER_NO_SHOW',
  SYSTEM_CANCELLED = 'SYSTEM_CANCELLED',
}
